/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sist_gest_cafe;

import DAO.categoriaDAO;
import modelo.Producto;
import DAO.productoDAO;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.AbstractCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Categoria;

/**
 *
 * @author Marcos Maria Sicilia
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        jTextFieldNombre.setEnabled(false);
        jComboBox.setEnabled(false);
        jTextFieldPrecio.setEnabled(false);
        jButtonGuardar.setEnabled(false);
        jButtonBorrar.setEnabled(false);

    }
    
    public void validarCampos(){
    
        String nombre = jTextFieldNombre.getText();
        String precio = jTextFieldPrecio.getText();
        String categoria = (String)jComboBox.getSelectedItem();
        if(!nombre.equals("") && !precio.equals("") && categoria != null)
            jButtonBorrar.setEnabled(true);     
        else
        {
            jButtonBorrar.setEnabled(false);
        }
    }
    
    public void limpiar(){
        
        setVisible(false);
        new Productos().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox<>();
        jButtonGuardar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCerrar = new javax.swing.JButton();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel1.setText("Productos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setText("Categoria");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        jLabelID.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabelID.setText("00");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 400, -1));

        jTextFieldPrecio.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 400, -1));

        jComboBox.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        getContentPane().add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 400, -1));

        jButtonGuardar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 150, -1));

        jButtonBorrar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButtonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 150, -1));

        jButtonLimpiar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clear.png"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 150, -1));

        jTable1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Precio"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 780, 710));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 40, 40, 30));

        jLabelDescripcion.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabelDescripcion.setText("*Seleccione el valor en la tabla para configurarlo*");
        getContentPane().add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ImagenRegistro2.png"))); // NOI18N
        jLabelFondo.setText("jLabel6");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        validarCampos();
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyReleased
        validarCampos();
    }//GEN-LAST:event_jTextFieldPrecioKeyReleased

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        
        Producto producto = new Producto();
        int id = Integer.parseInt(jLabelID.getText());
        producto.setId(id);
        producto.setNombre(jTextFieldNombre.getText());
        producto.setCategoria((String)jComboBox.getSelectedItem());
        producto.setPrecio(jTextFieldPrecio.getText());
        productoDAO.actualizar(producto);
        setVisible(false);
        new Productos().setVisible(true);
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
                      
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Producto> lista = productoDAO.getDatos();

        // Extraer datos
        Iterator<Producto> itr = lista.iterator();

        boolean valoresEnTabla = false; // Variable para verificar si se muestran valores en la tabla

        while (itr.hasNext()) {
            Producto productoObj = itr.next();
            dtm.addRow(new Object[]{productoObj.getId(), productoObj.getNombre(), productoObj.getCategoria(), productoObj.getPrecio()});
            valoresEnTabla = true; // Hay valores en la tabla
        }

        if (!valoresEnTabla) {
            int a = JOptionPane.showConfirmDialog(null, "Listado vacío. ¿Desea insertar nuevos productos?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                setVisible(false);
                new AniadirProducto().setVisible(true);
            }
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int a = JOptionPane.showConfirmDialog(null, "¿Seguro que desea actualizar el producto?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            jTextFieldNombre.setEnabled(true);
            jComboBox.setEnabled(true);
            jTextFieldPrecio.setEnabled(true);

            int indice = jTable1.getSelectedRow();
            TableModel modelo = jTable1.getModel();
            String id = modelo.getValueAt(indice, 0).toString();
            jLabelID.setText(id);
            String nombre = modelo.getValueAt(indice, 1).toString();
            jTextFieldNombre.setText(nombre);
            String categoria = modelo.getValueAt(indice, 2).toString();
            String precio = modelo.getValueAt(indice, 3).toString();
            jTextFieldPrecio.setText(precio);

            jButtonGuardar.setEnabled(true);
            jButtonBorrar.setEnabled(true);
            jComboBox.removeAllItems();
            ArrayList<Categoria> listaCategoria = categoriaDAO.getDatos();
            Iterator<Categoria> itr = listaCategoria.iterator();

            /*while (itr.hasNext()) {
                Categoria categoriaObj = itr.next();
                if (!categoriaObj.getNombre().equals(categoria) && categoriaObj.getNombre().equals(categoria)) {
                    jComboBox.addItem(categoriaObj.getNombre());
                }
            }*/

            while (itr.hasNext()) {
                Categoria categoriaObj = itr.next();
                jComboBox.addItem(categoriaObj.getNombre());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        
        String id = jLabelID.getText();
        int a = JOptionPane.showConfirmDialog(null, "¿Seguro que desea borrar este producto?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            productoDAO.borrar(id);
            setVisible(false);
            new Productos().setVisible(true);

        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
